name: dilosy
services:
    app:
        image: golang:1.21.10-alpine
        container_name: dilosy-app
        hostname: dilosy-app
        ports:
          - ${PORT}:80
        volumes:
            - .:/app:ro
            - ./src:/app/src:rw
            - ./storage:/app/storage:rw
        working_dir: /app
        command: sh -c "go build -C ./src -o main && ./src/main"

networks:
  default:
    name: dilosy-network
